// Command server is the entrypoint for jt-10.
//
// This file is yours (scaffolded): the scaffolder renders it once and never
// overwrites it. It loads configuration and constructs the logger, then hands
// both to package app — which owns the HTTP server lifecycle (managed).
// Capability modules extend the service by registering against package app, so
// you do not edit this file to wire them in.
package main

import (
	"context"
	"os"

	"jt-10/internal/app"
	"jt-10/internal/config"
	"jt-10/internal/logging"
)

func main() {
	cfg := config.Load()
	logger := logging.New(cfg)

	if err := app.Run(context.Background(), cfg, logger); err != nil {
		logger.Error("server exited with error", "err", err)
		os.Exit(1)
	}
}
